#!/bin/bash
SCRIPTDIR=$(dirname "$(readlink -f "$0")")
CARBONCOLLECTSO=$SCRIPTDIR/../bin/carbon-collect.so
CXX=$SCRIPTDIR/../../../libs/llvm/bin/clang++

#
# we define __extern_always_inline because of a bug in glibc which results
# in compiler errors when using clang:
#
# https://sourceware.org/bugzilla/show_bug.cgi?id=14952
#
# we pass -no-integrated-as to clang because of trouble dealing with inline
# assembly. see freebsd thread on the error encountered:
#
# https://lists.freebsd.org/pipermail/freebsd-ports/2012-September/077996.html
#

#
# XXX: code-carbon root directory *must* be installed at ${HOME}/code-carbon.
# This hack was necessary to support the ultimate hack of altering the
# system-wide /usr/bin/gcc, while still supporting multiple users using
# code-carbon on the same machine
#

#
# check if the working directory is under ~/code-carbon/examples/apps/bin/s
# if so, execute clang.
#
python -c "import sys; import os.path; p=os.path.relpath(\"${PWD}\", \"${HOME}/code-carbon/examples/apps/bin/s\"); sys.exit(0 if p == \".\" or p[:2] != \"..\" else 1)"
if [ $? -eq 0 ]
then
  exec ${CXX} "$@" \
    -O0 -g \
    -no-integrated-as \
    -D__extern_always_inline=inline
fi

#
# fallback to gcc-4.7
#
exec /usr/bin/g++-4.7 "$@" '-O0' '-g'
